(* Funcy Reference Grammar *)

root = { stmt_func }, EOF ;

stmt = stmt_func | stmt_block | stmt_nop | stmt_print | stmt_expr ;

stmt_func  = "func", IDENTIFIER, "(", [ IDENTIFIER, { ",", IDENTIFIER } ], ")", stmt_block ;
stmt_block = "{", { stmt }, "}" ;
stmt_nop   = ";" ;
stmt_print = "print", expr_paren, ";" ;
stmt_expr  = expr, ";" ;

expr_paren = "(", expr, ")" ;
expr       = expr_primary ;

expr_primary = expr_paren | LITERAL_INT | IDENTIFIER ;
